services:
  db:
    image: pgvector/pgvector:pg17
    container_name: wheretf-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wheretf

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: wheretf-backend

    ports:
      - "8000:8000"

    depends_on:
      - db

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/wheretf

volumes:
  postgres_data: