"""create_file_relationships_table

Revision ID: 2f98f76cb765
Revises: cdcdffd36592
Create Date: 2026-06-11 16:18:13.091065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f98f76cb765'
down_revision: Union[str, Sequence[str], None] = 'cdcdffd36592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('target_file_id', sa.UUID(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), server_default='semantic_similarity', nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_file_id', 'target_file_id', name='uq_file_relationship')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_relationships')
    # ### end Alembic commands ###
